name: Test

on:
  push:
    branches-ignore: [ "main" ]

env:
  NODE_VERSION: ">=18.12.1"

permissions:
  id-token: write
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Build Transformer
        run: bun run build
      - name: Change Permissions on Dist
        run: chmod -R 777 dist
      - name: List Build Directory
        run: ls -la dist
      - name: Start Transformer Shell
        run: |
          docker-compose -f test/docker/docker-compose.yaml up -d
          chmod +x test/docker/await-testing.sh
          test/docker/await-testing.sh
      - name: Test
        env:
          HOST_ADDRESS: 172.17.0.1
        run: bun run test --runInBand --detectOpenHandles --forceExit
